### ISSUE TITLE
Why not use the file manager and drag-and-drop?

### ISSUE THREAD

**Issue by probonopd** [NXOS/nxs#1]
Why not use the file manager and drag-and-drop?

**Comment by luis-lavaire** [comment]
What do you exactly mean @probonopd? Place the AppImages on some location with DnD?

**Comment by probonopd** [comment]
Yes. After all, AppImages were specifically made so that you don't need a package manager, so I was just wondering why people want one anyway...

**Comment by luis-lavaire** [comment]
Oh, OK. The intention behind `nxs` is to use it in case you don't have a graphical interface and automating doing `wget ...`, `mv ...`, etc. Secondly, to centralize the distribution of some applications. But in a very wide and general sense, to automate the tasks and help the user keep the applications he installs organized.
